// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPYEuV6jaTSDZ_SI5VXv1juT370gXb5E0',
    appId: '1:137110090365:web:432c4de1800b37927f7714',
    messagingSenderId: '137110090365',
    projectId: 'you-app-c6b1f',
    authDomain: 'you-app-c6b1f.firebaseapp.com',
    storageBucket: 'you-app-c6b1f.firebasestorage.app',
    measurementId: 'G-VES7J8SZLF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpy0WqLR154rU6M4XkpW5uwc7Oxk5giwo',
    appId: '1:137110090365:android:e5ce79a4b3107dba7f7714',
    messagingSenderId: '137110090365',
    projectId: 'you-app-c6b1f',
    storageBucket: 'you-app-c6b1f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6oUlXt8OCScNuUiDLShpH30I5YnfSo2M',
    appId: '1:137110090365:ios:d958ff82f97409597f7714',
    messagingSenderId: '137110090365',
    projectId: 'you-app-c6b1f',
    storageBucket: 'you-app-c6b1f.firebasestorage.app',
    iosBundleId: 'com.example.youApp',
  );
}
